### ISSUE TITLE
Styling results from wps

### ISSUE THREAD

**Issue by mazimweal** [3liz/lizmap-wps-web-client-module#8]
Hi
am still wondering, how possible is it to style results of the WPS in lizmap?
Allan

**Comment by dmarteau** [comment]
In the WPS provider directory (given by https://py-qgis-wps.readthedocs.io/en/latest/configuration.html#processing-providers-module-path) create a json file with the following structure:
```
  {
         'algid': {
             'outputname': file.qml
             ...
        }
        ...
}
```
Basically the file associate the layer returned in  `outputname` from the algorithm to a qml file - you may define this qml with Qgis desktop. 

Note that this is part is missing from the doc because it is still experimental and will be subject to change.  For now this configuration is defined globally but you will be able (soon) to define a configuration per processing provider.

**Comment by dmarteau** [comment]
Added documentation about styling WPS layers: https://github.com/3liz/py-qgis-wps/commit/5c4d8bd35a335d96fcb0509ef9ed65aaf119ba13

See  https://py-qgis-wps.readthedocs.io/en/latest/styles.html
